swagger: "2.0"
info:
  title: "go-rest-api"
  version: "1.0.0"
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
definitions:
  $ref: ./definitions/index.yml
paths:
  $ref: ./paths/index.yml
